print("nihao mme")
print("nihao mme")
print("nihao mme")
print("nihao mme")
print("i love youjjjj")
print("i love youjjjj")
print("i love youjjjj")
print("i love youjjjj")
print("i love youjjjj")
print("i love youjjjj")
